#!/bin/sh -e

#
# Remove broken maintainer scripts of mdev 1.0.0
#
case "$1" in
  install|upgrade)
    if dpkg --compare-versions "$2" le-nl 1.0.0; then
      rm -f /var/lib/dpkg/info/mdev.prerm
      rm -f /var/lib/dpkg/info/mdev.postinst
    fi;;
esac
